//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Firmalar
    {
        public Firmalar()
        {
            this.Araba = new HashSet<Araba>();
            this.Otel = new HashSet<Otel>();
            this.Ucus = new HashSet<Ucus>();
            this.Yorum = new HashSet<Yorum>();
        }
    
        public int firmaId { get; set; }
        public string firmaAdi { get; set; }
        public string firmaTipi { get; set; }
        public Nullable<int> firmaPuani { get; set; }
        public string firmaAciklamasi { get; set; }
        public string firmaAdresi { get; set; }
        public int sehirId { get; set; }
    
        public virtual ICollection<Araba> Araba { get; set; }
        public virtual Sehir Sehir { get; set; }
        public virtual ICollection<Otel> Otel { get; set; }
        public virtual ICollection<Ucus> Ucus { get; set; }
        public virtual ICollection<Yorum> Yorum { get; set; }
    }
}
