//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HavaDurumu
    {
        public int havaId { get; set; }
        public string gun { get; set; }
        public string durum { get; set; }
        public string sicaklik { get; set; }
        public int sehirId { get; set; }
    
        public virtual Sehir Sehir { get; set; }
    }
}
