//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sehir
    {
        public Sehir()
        {
            this.Firmalar = new HashSet<Firmalar>();
            this.HavaDurumu = new HashSet<HavaDurumu>();
            this.Ucus = new HashSet<Ucus>();
            this.Ucus1 = new HashSet<Ucus>();
        }
    
        public int sehirId { get; set; }
        public string sehirAdi { get; set; }
    
        public virtual ICollection<Firmalar> Firmalar { get; set; }
        public virtual ICollection<HavaDurumu> HavaDurumu { get; set; }
        public virtual ICollection<Ucus> Ucus { get; set; }
        public virtual ICollection<Ucus> Ucus1 { get; set; }
    }
}
