//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ucus
    {
        public int ucusId { get; set; }
        public System.TimeSpan saat { get; set; }
        public int fiyat { get; set; }
        public Nullable<System.TimeSpan> ucusSuresi { get; set; }
        public string tarih { get; set; }
        public string model { get; set; }
        public string mesafe { get; set; }
        public int kalkis { get; set; }
        public int varis { get; set; }
        public int firmaId { get; set; }
    
        public virtual Firmalar Firmalar { get; set; }
        public virtual Sehir Sehir { get; set; }
        public virtual Sehir Sehir1 { get; set; }
    }
}
