//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        private string yorm;
        private int id;

        public int yorumId { get; set; }
        public string yorum1 { get; set; }
        public int firmaId { get; set; }
        public Yorum() { }

        public Yorum(string yorm, int id)
        {
            // TODO: Complete member initialization
            this.yorm = yorm;
            this.id = id;
        }
        public virtual Firmalar Firmalar { get; set; }
    }
}
